export const projects = [
    {
        name: "Sales Performance Dashboard",
        count: "01",
        date: 2026,
        desc_title: 'Data Analytics Project',
        description: 'An interactive Power BI dashboard for analyzing sales performance, profitability and customer segments through KPIs, trends, visualizations and dynamic filters.',
        tech: "Using Power BI + DAX + Excel",
        src: "/images/IMG.png",
        link: "https://github.com/erkanuz/sales-performance-dashboard",
    },
    {
        name: "Boatly",
        count: "02",
        date: 2024,
        desc_title: 'Frontend Project',
        description: 'Boatly is a responsive boat booking website that allows users to explore boat tours, view available options and book a boat for a specific date and time.',
        tech: "Using React + TypeScript + Tailwind CSS",
        src: "/images/boatly.png",
        link: "https://github.com/erkanuz/boat-rental",
    },
    {
        name: "Netflix Clone",
        count: "03",
        date: 2023,
        desc_title: 'Fullstack Project',
        description: 'The Netflix clone is a responsive app with Firebase authentication, personal movie list management, and modals for detailed movie info and trailers, offering extensive movie browsing.',
        tech: "Using Next.js + Tailwind CSS + TMDB API + Firebase.",
        src: "https://user-images.githubusercontent.com/78959562/245288833-a4490069-3b37-4eba-9244-60bda2028747.png",
        link: "https://netflix-clone-lilac-five.vercel.app/welcome",
    },
    {
        name: "GOTHIC",
        count: "04",
        date: 2023,
        desc_title: 'Fullstack Project',
        description: 'The Gothic e-commerce website offers a modern design with cart management, product details, user authentication, search, sorting, dark mode, 3D objects, star ratings, and a modal preview. It uses Redux for cart functionality and Firebase/Firestore for user data and order processing.',
        tech: "Using React.js & Tailwind CSS & Firebase & Redux",
        src: "https://user-images.githubusercontent.com/78959562/225651197-5982a2f8-75f1-468c-8f45-d0aebe14d419.png",
        link: "https://erkanuz.github.io/gothic/",
    },
]