export const projects = [
    {
        name: "Next Dashboard",
        date: 2023,
        desc_title: 'Fullstack Project',
        description: 'The Next Dashboard features six pages: overview of revenue and users, user management, product details with charts, order tracking, and forms for adding and updating orders. It includes CRUD operations, validation, search, and sorting.',
        tech: "Using Next.js + Tailwind CSS + MongoDB",
        src: "https://user-images.githubusercontent.com/78959562/263232035-86380114-002d-4bae-adae-ff6fc73abe11.png",
        link: "https://next-dashboard-erkanuz.vercel.app/",
    },
    {
        name: "Netflix Clone",
        date: 2023,
        desc_title: 'Fullstack Project',
        description: 'The Netflix clone is a responsive app with Firebase authentication, personal movie list management, and modals for detailed movie info and trailers, offering extensive movie browsing.',
        tech: "Using Next.js + Tailwind CSS + TMDB API + Firebase.",
        src: "https://user-images.githubusercontent.com/78959562/245288833-a4490069-3b37-4eba-9244-60bda2028747.png",
        link: "https://netflix-clone-erkanuz.vercel.app/welcome",
    },
    {
        name: "PQR Generator",
        date: 2023,
        desc_title: 'Fullstack Project',
        description: 'The PQR Generator creates random passwords with customizable options, generates QR codes, and includes a dark mode feature.',
        tech: "Using React.js & Tailwind CSS.",
        src: "https://user-images.githubusercontent.com/78959562/203557499-d7c17c54-d120-415f-be84-cfa77c4a4a84.png",
        link: "https://erkanuz.github.io/PQR-Generator/",
    },
    {
        name: "GOTHIC",
        date: 2023,
        desc_title: 'Fullstack Project',
        description: 'The Gothic e-commerce website offers a modern design with cart management, product details, user authentication, search, sorting, dark mode, 3D objects, star ratings, and a modal preview. It uses Redux for cart functionality and Firebase/Firestore for user data and order processing.',
        tech: "Using React.js & Tailwind CSS & Firebase & Redux",
        src: "https://user-images.githubusercontent.com/78959562/225651197-5982a2f8-75f1-468c-8f45-d0aebe14d419.png",
        link: "https://erkanuz.github.io/gothic/",
    },
 ]