import { Inter, Dancing_Script, Great_Vibes } from 'next/font/google'

import './globals.scss'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const dancig = Dancing_Script({ 
  subsets: ['latin'],
  variable: '--font-dancing'
})
const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-greatVibes'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${dancig.variable} ${greatVibes.variable}`}>{children}</body>
    </html>
  )
}
