export * from './Hero/index'
export * from './Skills/index'
export * from './Projects/index'
export * from './Paralax/index'
export * from './Contacts/index'
export * from './Footer/index'

export * from './Main/index'
export * from './Education/index'
export * from './Expertise/index'
export * from './HowIWork/index'
export * from './ContactMe/index'