export * from './Hero/index'
export * from './Skills/index'
export * from './Projects/index'
export * from './Paralax/index'
export * from './Services/index'
export * from './Stages/index'
export * from './Contacts/index'
export * from './Footer/index'